# Main testing image
FROM ruby:alpine

# Chef Inspec - 
ARG EXPEDITOR_VERSION
ARG VERSION=4.16.0
ARG GEM_SOURCE=https://rubygems.org
# Chef Inspec - Allow VERSION below to be controlled by either VERSION or EXPEDITOR_VERSION build arguments
ENV VERSION ${EXPEDITOR_VERSION:-${VERSION}}

ARG KUBECTL_VERSION=v1.25.0
ARG TERRAFORM_VERSIONS="1.2.8 0.14.11 0.13.7 0.12.31"
ARG TERRAFORM_DEFAULT_VERSION="1.2.8"
ARG TERRAGRUNT_VERSION="v0.38.8"

# Update local caches repo and upgrade the OS
RUN apk update && \
    apk --no-cache add \

# Common required packages
apk-tools \
aws-cli \
bash \
bind-tools \
build-base \
ca-certificates \
coreutils \
curl \
gcc \
git \
go \
jq \
py-pip \
make \
npm \
openssh \
python3 \
unzip \
wget

# terraform and tfenv
# How to use within your CD pipepine?
#   export TF_VERSION=0.15.5;
#   tfenv use 0.15.5

RUN git clone https://github.com/tfutils/tfenv.git ~/.tfenv && \
    ln -s ~/.tfenv/bin/* /usr/local/bin && \

for TERRAFORM_VERSION in ${TERRAFORM_VERSIONS}; do tfenv install ${TERRAFORM_VERSION}; done && \
    tfenv use ${TERRAFORM_DEFAULT_VERSION}

# terragrunt
RUN wget -q https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_VERSION}/terragrunt_darwin_amd64 \
    -O /usr/local/bin/terragrunt && chmod +x /usr/local/bin/terragrunt

# kubectl
RUN wget -q https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl -O /usr/local/bin/kubectl && \
    chmod +x /usr/local/bin/kubectl

# KOPS
RUN wget -q https://github.com/kubernetes/kops/releases/download/${KOPS_VER}/kops-linux-amd64 \
    -O /usr/local/bin/kops && chmod +x /usr/local/bin/kops

# helm

# chef inspec
RUN mkdir -p /share
RUN apk add --update build-base libxml2-dev libffi-dev git openssh-client
RUN gem install --no-document --source ${GEM_SOURCE} --version ${VERSION} inspec
RUN gem install --no-document --source ${GEM_SOURCE} --version ${VERSION} inspec-bin && \
    gem install aws-sdk
RUN inspec --chef-license=accept && \
    inspec plugin install inspec-iggy
RUN apk del build-base
VOLUME ["/share"]
WORKDIR /share

# Cleanup after installation
RUN apk del wget && \
rm -rf /tmp/* && \
rm -rf /var/cache/apk/*

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8
