name: ci

# Controls when the workflow will run
on:
  # Build weekly
  schedule:
    - cron: '0 21 * * 0'
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  # tags:
  #   - [0-9]+.[0-9]+.[0-9]+*
  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# JOBS section
jobs:
# Common image section
  build-alpine-common:
    name: build-alpine-common
    runs-on: ubuntu-latest
    steps:
      -
        name: Alpine - Checkout 
        uses: actions/checkout@v3
      -
        name: Alpine - Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Alpine - Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Alpine - Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Alpine - Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.common
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/deployer:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/deployer:1.0.0
          labels: "alpine, terraform, helm, tfenv, deployer"
          # labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/maintenance-pod:buildcache
          # cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/maintenance-pod:buildcache,mode=max

# Testing image section
  build-alpine-testing:
    name: build-alpine-testing
    runs-on: ubuntu-latest
    steps:
      -
        name: Alpine - Checkout 
        uses: actions/checkout@v3
      -
        name: Alpine - Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Alpine - Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Alpine - Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Alpine - Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.testing
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/testing:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/testing:1.0.0
          labels: "testing"
          # labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/maintenance-pod:buildcache
          # cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/maintenance-pod:buildcache,mode=max
